In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# display settings
from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [2]:
np.random.seed(42)
t1 = np.random.randint(1, 100, 1000)
t2 = np.random.randint(1, 300, 300)
t3 = np.random.randint(1, 1000, 200)

m1 = np.random.randint(1, 20, 1000)
m2 = np.random.randint(5, 20, 30)
m3 = np.random.randint(10, 20, 200)

# print(t1 / m1)
# print(t2 / m2)
# print(t3 / m3)
# t1, t2, t3, m1, m2, m3

In [3]:
pt1 = np.random.randint(1, 10, 50)
d1 = pt1 * 1.2 + np.random.randn(50)
pt1, d1, pt1 / d1

(array([5, 3, 7, 5, 8, 1, 3, 3, 9, 5, 9, 9, 1, 2, 5, 4, 9, 7, 6, 7, 1, 1,
        8, 2, 9, 7, 6, 1, 1, 2, 6, 6, 2, 1, 5, 5, 2, 6, 9, 2, 2, 3, 7, 6,
        8, 8, 6, 3, 3, 1]),
 array([ 5.35403582,  2.80080799,  7.91725648,  5.04667139,  9.72267032,
         2.82467846,  3.92307927,  3.3476465 , 10.50818873,  4.43680919,
        11.68310978, 10.7221628 ,  1.01952009,  5.59310757,  6.29875291,
         4.04820895, 10.3736424 ,  9.54844571,  7.31327041,  6.96172202,
         2.11922893,  0.53185591, 11.47329778,  3.48004807, 10.3526781 ,
         9.68101636,  7.26785551,  2.05277368,  1.68473282,  1.55364335,
         6.55645017,  8.22996082,  2.06522467,  0.79635154,  5.04487742,
         6.42359907,  4.46252492,  6.13246709, 10.82421946,  3.81222056,
         2.32035861,  4.0523718 ,  7.33760647,  7.6283071 ,  9.41285573,
        10.58573   ,  8.38738605,  6.18956364,  4.17963317,  1.52579632]),
 array([0.93387496, 1.07111948, 0.88414466, 0.99075204, 0.82281922,
        0.3540226 , 0.76

In [4]:
from sklearn.preprocessing import minmax_scale

processing_time_1 = []
processing_time_2 = []
due_time = []
stage1_machines = []
stage2_machines = []

for i in range(len(t1)):
    
    if (t1[i] / m1[i] > 15):
        continue
        
    
    pt1 = np.random.randint(1, 100, t1[i]) / 10
#     print(pt1)
    pt2 = (np.random.randint(0, 120, t1[i])) / 10 - 2
    
    # make nan probability larger
    pt2[pt2 < 0] = 0
#     print("pt2", pt2)
#     print(pt1 + pt2)
    
    # positive correlation between processing time and due time + error
    # try to lower the possibility of doomed-to-be tardy jobs
    d1 = (pt1 + pt2) * 1.2 + np.random.randn(t1[i]) * 5 + 2
    d1 = d1.round(decimals=1)
    
    # upper and lower bound
    d1[d1 < 1] = 1
    d1[d1 > 24] = 24
    
    
    if (sum(pt1 + pt2) > 1.5 * m1[i] * 24):
        continue
        
    if (sum(pt1 + pt2 > d1) > t1[i] * 0.2):
        continue
    
#     print("d1", d1)
#     print("job num:", t1[i])
#     print("less than:", sum(pt1 + pt2 > d1))
#     print("operation time:", m1[i] * 24)
#     print("due time:", sum(d1))
#     print("process time:", sum(pt1 + pt2))
    
#     plt.scatter(pt1 + pt2, d1)
#     plt.xlabel("total processing time")
#     plt.ylabel("due time");
#     plt.show()
    
    processing_time_1.append(pt1)
    processing_time_2.append(pt2)
    due_time.append(d1)
    
    # machine
    unable = np.random.randint(1, t1[i], int(t1[i] / 3))
    
    stage1_machine = ""
    for m in range(1, m1[i] + 1):
        stage1_machine += str(m) + ","
    stage1_machine = stage1_machine.rstrip(",")
    
    stage2_machine = ""
    for m in range(1, m1[i] + 1):
        if m in unable:
            continue
        stage2_machine += str(m) + ","
    stage2_machine = stage2_machine.rstrip(",")
    
    stage1_machines.append(stage1_machine)
    stage2_machines.append(stage2_machine)
    
#     print("stage 1 machine:", stage1_machine)
#     print("stage 2 machine:", stage2_machine)
    
print(len(due_time))

184


In [5]:
if os.getcwd() != '/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase':
    os.chdir('/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase')
if not os.path.exists('testcases'):
    os.makedirs('testcases')

os.chdir("testcases")
os.getcwd()

'/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase/testcases'

In [7]:
for i in range(len(due_time)):
    df = pd.DataFrame(due_time[i], columns=["Due Time"])
    df["Stage-1 Processing Time"] = processing_time_1[i]
    df["Stage-2 Processing Time"] = processing_time_2[i]
    df["Stage-1 Machines"] = stage1_machines[i]
    df["Stage-2 Machines"] = stage2_machines[i]
    df.index.names = ['Job ID']
    
    no_stage2 = (df["Stage-2 Processing Time"] == 0)
    df.loc[no_stage2, "Stage-2 Machines"] = np.nan
    print(df[no_stage2])   
    
    df.to_csv("instance " + str(i + 1) + ".csv")

        Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
Job ID                                                               
3         7.6000                   3.5000                   0.0000   
6        11.5000                   4.5000                   0.0000   

            Stage-1 Machines Stage-2 Machines  
Job ID                                         
3       1,2,3,4,5,6,7,8,9,10              NaN  
6       1,2,3,4,5,6,7,8,9,10              NaN  
        Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
Job ID                                                               
6        10.6000                   2.4000                   0.0000   
17        1.9000                   1.2000                   0.0000   
21       12.3000                   8.2000                   0.0000   
23       14.9000                   7.5000                   0.0000   
28       18.0000                   9.5000                   0.0000   
29        8.4000                   9.

        Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
Job ID                                                               
0        24.0000                   9.9000                   0.0000   

            Stage-1 Machines Stage-2 Machines  
Job ID                                         
0       1,2,3,4,5,6,7,8,9,10              NaN  
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
        Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
Job ID                                                               
5        11.4000                   8.7000                   0.0000   
6         1.0000                   3.8000                   0.0000   
25        1.0000                   0.7000                   0.0000   

               Stage-1 Machines Stage-2 Machines  
Job ID                                            
5       1,2,3,4,5,6,7,8,9,10,11              NaN  
6       1