In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# display settings
from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [140]:
np.random.seed(42)
t1 = np.random.randint(1, 100, 1000)
t2 = np.random.randint(1, 300, 300)
t3 = np.random.randint(1, 1000, 200)

m1 = np.random.randint(1, 20, 1000)
m2 = np.random.randint(5, 20, 30)
m3 = np.random.randint(10, 20, 200)

# print(t1 / m1)
# print(t2 / m2)
# print(t3 / m3)
# t1, t2, t3, m1, m2, m3

In [128]:
pt1 = np.random.randint(1, 10, 50)
d1 = pt1 * 1.2 + np.random.randn(50)
pt1, d1, pt1 / d1

(array([4, 7, 2, 3, 1, 5, 1, 8, 1, 1, 2, 2, 6, 7, 5, 1, 1, 3, 2, 5, 6, 7,
        4, 7, 8, 1, 6, 8, 5, 4, 2, 6, 6, 1, 9, 6, 3, 4, 4, 3, 3, 3, 4, 7,
        4, 9, 1, 8, 7, 2]),
 array([ 5.28197914,  9.32645636,  1.56241861,  4.27718607,  3.07231912,
         6.39637394,  0.5743837 ,  9.07753852,  1.2130339 ,  1.57776959,
         2.4628246 ,  2.90159637,  7.05305461,  8.58062297,  6.96481058,
         0.13516885,  1.3087118 ,  3.70576365,  3.32066672,  5.77327754,
         7.85304831,  9.50268747,  2.95019706,  9.56863124,  8.6146182 ,
         0.10605959,  4.32054311,  8.79682233,  5.99514306,  4.41667669,
         1.93747314,  6.08750265,  8.0672295 ,  2.15841384, 11.21811852,
         5.31347195,  5.87334516,  4.94697465,  5.3396092 ,  2.10170436,
         3.58855655,  4.01335409,  4.65910145,  9.27216186,  6.10034515,
         9.45647624,  2.05012058,  9.99433995,  8.39530401,  0.82918802]),
 array([0.7572919 , 0.75055302, 1.28006668, 0.70139572, 0.32548702,
        0.78169289, 1.74

In [148]:
from sklearn.preprocessing import minmax_scale

processing_time_1 = []
processing_time_2 = []
due_time = []
stage1_machines = []
stage2_machines = []

for i in range(len(t1)):
    
    if (t1[i] / m1[i] > 15):
        continue
        
    
    pt1 = np.random.randint(1, 100, t1[i]) / 10
#     print(pt1)
    pt2 = (np.random.randint(0, 120, t1[i])) / 10 - 2
    
    # make nan probability larger
    pt2[pt2 < 0] = 0
#     print("pt2", pt2)
#     print(pt1 + pt2)
    
    # positive correlation between processing time and due time + error
    # try to lower the possibility of doomed-to-be tardy jobs
    d1 = (pt1 + pt2) * 1.2 + np.random.randn(t1[i]) * 5 + 2
    d1 = d1.round(decimals=1)
    
    # upper and lower bound
    d1[d1 < 1] = 1
    d1[d1 > 24] = 24
    
    
    if (sum(pt1 + pt2) > 1.5 * m1[i] * 24):
        continue
        
    if (sum(pt1 + pt2 > d1) > t1[i] * 0.2):
        continue
    
#     print("d1", d1)
#     print("job num:", t1[i])
#     print("less than:", sum(pt1 + pt2 > d1))
#     print("operation time:", m1[i] * 24)
#     print("due time:", sum(d1))
#     print("process time:", sum(pt1 + pt2))
    
#     plt.scatter(pt1 + pt2, d1)
#     plt.xlabel("total processing time")
#     plt.ylabel("due time");
#     plt.show()
    
    processing_time_1.append(pt1)
    processing_time_2.append(pt2)
    due_time.append(d1)
    
    # machine
    unable = np.random.randint(1, t1[i], int(t1[i] / 3))
    
    stage1_machine = ""
    for m in range(1, m1[i] + 1):
        stage1_machine += str(m) + ","
    stage1_machine.rstrip(",")
    
    stage2_machine = ""
    for m in range(1, m1[i] + 1):
        if m in unable:
            continue
        stage2_machine += str(m) + ","
    stage2_machine.rstrip(",")
    
    stage1_machines.append(stage1_machine)
    stage2_machines.append(stage2_machine)
    
#     print("stage 1 machine:", stage1_machine)
#     print("stage 2 machine:", stage2_machine)
    
print(len(due_time))

190


In [142]:
if os.getcwd() != '/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase':
    os.chdir('/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase')
if not os.path.exists('testcases'):
    os.makedirs('testcases')

os.chdir("testcases")
os.getcwd()

'/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase/testcases'

In [157]:
for i in range(len(due_time)):
    df = pd.DataFrame(due_time[i], columns=["Due Time"])
    df["Stage-1 Processing Time"] = processing_time_1[i]
    df["Stage-2 Processing Time"] = processing_time_2[i]
    df["Stage-1 Machines"] = stage1_machines[i]
    df["Stage-2 Machines"] = stage2_machines[i]
    
    no_stage2 = (df["Stage-2 Processing Time"] == 0)
    df.loc[no_stage2, "Stage-2 Machines"] = np.nan
    print(df[no_stage2])   
    
    df.to_csv("instance " + str(i + 1) + ".csv")

    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
3     8.9000                   2.5000                   0.0000   
6     1.0000                   4.8000                   0.0000   
12   14.5000                   3.7000                   0.0000   

         Stage-1 Machines Stage-2 Machines  
3   1,2,3,4,5,6,7,8,9,10,              NaN  
6   1,2,3,4,5,6,7,8,9,10,              NaN  
12  1,2,3,4,5,6,7,8,9,10,              NaN  
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
8    15.3000                   8.8000                   0.0000   
10   15.3000                   9.9000                   0.0000   
28    4.4000                   5.3000                   0.0000   
50   17.3000                   5.2000                   0.0000   
57    1.4000                   1.1000                   0.0000   

                              Stage-1 Machines Stage-2 Machines  
8   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN  
10  1,2,3,4,5,6,7,8,9,10,1

    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
6     4.8000                   2.6000                   0.0000   
8     1.0000                   0.7000                   0.0000   
25    4.5000                   3.4000                   0.0000   
33    5.3000                   1.6000                   0.0000   

               Stage-1 Machines Stage-2 Machines  
6   1,2,3,4,5,6,7,8,9,10,11,12,              NaN  
8   1,2,3,4,5,6,7,8,9,10,11,12,              NaN  
25  1,2,3,4,5,6,7,8,9,10,11,12,              NaN  
33  1,2,3,4,5,6,7,8,9,10,11,12,              NaN  
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1     4.2000                   8.5000                   0.0000   
4    14.8000                   8.6000                   0.0000   
9     2.5000                   0.1000                   0.0000   
11    1.5000      